#!/bin/bash

SDIR=../erlhw
EXCLUDES=dump_excludes


TDIR=RaspiBox
TADDR=192.168.1.63
TUSR=pi

export RSYNC_PASSWORD=raspberry

OPTS="--force --ignore-errors --exclude-from=$EXCLUDES
       -avz"

##cd ..; find erlhw | grep -v .git | grep -v ct_run | xargs -J% cp -R % /Volumes/Home\ Directory/RaspiBox

rsync ${OPTS}  ${SDIR} ${TUSR}@${TADDR}:/${TDIR}
